# Generated by Django 5.1.3 on 2024-11-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
                ('club_location', models.CharField(max_length=255)),
                ('established_year', models.IntegerField()),
                ('admin_password', models.CharField(max_length=255)),
                ('analyst_password', models.CharField(max_length=255)),
            ],
        ),
    ]
