# Generated by Django 5.1.3 on 2024-11-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach'), ('gk_coach', 'Goalkeeper Coach'), ('physical_coach', 'Physical Coach'), ('fitness_coach', 'Fitness Coach')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='club.footballclub')),
            ],
        ),
    ]
